apiVersion: v1
kind: Pod

metadata:
  name: demo-two-containers

spec:
  restartPolicy: Never

  volumes:
  - name: shared-data
    emptyDir: {}

  containers:
  - name: ngnix-container
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html

  - name: debian-container
    image: debian
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: ["-c", "echo Hello from debian container > /pod-data/index.html"]

  - name: tomcat-container
    image: tomcat:8.0
    command: ["sh", "-c", "/root/apache-tomcat-8.0/bin/start.sh"]
    volumeMounts:
    - name: shared-data
      mountPath: /root/apache-tomcat-8.0/webapps
    ports:
      - containerPort: 8080
        hostPort: 8081
